/*
 *Auto-generated by gitVersion(Author: feiguoyou@hotmail.com), Don't Modify it!
 */
#ifndef _VERSION_H_
#define _VERSION_H_

#define LELINK_VERSION          "ee64dc7"
#define LELINK_MODIFY_FLAG      "1"
#define LELINK_COMMIT_ID        "git"
#define SW_BASE_VER             "1.0.0"
#define SW_VERSION              SW_BASE_VER"."LELINK_COMMIT_ID"."LELINK_VERSION"."LELINK_MODIFY_FLAG

#endif //  _VERSION_H_
