/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_letv_lelink_LeLink */

#ifndef _Included_com_letv_lelink_LeLink
#define _Included_com_letv_lelink_LeLink
#ifdef __cplusplus
extern "C" {
#endif
#undef com_letv_lelink_LeLink_MSG_TYPE_LOCALREQUEST
#define com_letv_lelink_LeLink_MSG_TYPE_LOCALREQUEST 1L
#undef com_letv_lelink_LeLink_MSG_TYPE_LOCALRESPOND
#define com_letv_lelink_LeLink_MSG_TYPE_LOCALRESPOND 2L
#undef com_letv_lelink_LeLink_MSG_TYPE_REMOTEREQUEST
#define com_letv_lelink_LeLink_MSG_TYPE_REMOTEREQUEST 3L
#undef com_letv_lelink_LeLink_MSG_TYPE_REMOTERESPOND
#define com_letv_lelink_LeLink_MSG_TYPE_REMOTERESPOND 4L
/*
 * Class:     com_letv_lelink_LeLink
 * Method:    getSDKInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_letv_lelink_LeLink_getSDKInfo
  (JNIEnv *, jclass);

/*
 * Class:     com_letv_lelink_LeLink
 * Method:    init
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_letv_lelink_LeLink_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_letv_lelink_LeLink
 * Method:    airConfig
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_letv_lelink_LeLink_airConfig
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_letv_lelink_LeLink
 * Method:    send
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_letv_lelink_LeLink_send
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
