#!/bin/bash

if [ $# -lt 3 ]; then
	echo $0 Error, must have 3 args
    echo $0 ProjectPath TemplateFile NewFile
	exit
fi
WK_PATH=$1
VER_IN=$2
VER_OUT=$3

SVN_VER=$(svn info $WK_PATH | awk '/Last Changed Rev/' | awk '{print $4}')
SVN_MDF_FLAG=$(svn st $WK_PATH | awk '{if(match($0, /^[\s,A,C,D,M,R,X,!,~]/)) {print "1"; exit;}}') # [\s,A,C,D,M,R,X,?,!,~] , 全部标识
if [ -n "$SVN_MDF_FLAG" ]; then
SVN_MDF_FLAG="1"
else
SVN_MDF_FLAG="0"
fi

echo "SVN VERSION: $SVN_VER"
echo "SVN CHANGED: $SVN_MDF_FLAG"

sed -e "s/\\""\$WCREV\\""\$/$SVN_VER/g" -e "s/\\""\$WCMODS.*\\""\$/$SVN_MDF_FLAG/g" $VER_IN > $VER_OUT
