/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_letv_lelive_LeWrapper */

#ifndef _Included_com_letv_lelive_LeWrapper
#define _Included_com_letv_lelive_LeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_letv_lelive_LeWrapper
 * Method:    init
 * Signature: (Lcom/letv/lelive/LeDelegate;)I
 */
JNIEXPORT jint JNICALL Java_com_letv_lelive_LeWrapper_init
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_letv_lelive_LeWrapper
 * Method:    exit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_letv_lelive_LeWrapper_exit
  (JNIEnv *, jobject);

/*
 * Class:     com_letv_lelive_LeWrapper
 * Method:    airconfigCtrl
 * Signature: (Lcom/letv/lelive/LeData;)I
 */
JNIEXPORT jint JNICALL Java_com_letv_lelive_LeWrapper_airconfigCtrl
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_letv_lelive_LeWrapper
 * Method:    postDiscovery
 * Signature: (Lcom/letv/lelive/LeData;)I
 */
JNIEXPORT jint JNICALL Java_com_letv_lelive_LeWrapper_postDiscovery
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_letv_lelive_LeWrapper
 * Method:    postDevAuth
 * Signature: (Lcom/letv/lelive/LeData;)I
 */
JNIEXPORT jint JNICALL Java_com_letv_lelive_LeWrapper_postDevAuth
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_letv_lelive_LeWrapper
 * Method:    post
 * Signature: (Lcom/letv/lelive/LeData;)I
 */
JNIEXPORT jint JNICALL Java_com_letv_lelive_LeWrapper_post
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
